name: Fix-release Workflow

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version"
        required: true
        type: string

env:
  RELEASE_VERSION: ${{ github.event.inputs.release_version }}
  YCR_REGISTRY_ID: ${{ secrets.YCR_ID }}
  YCR_TOKEN: ${{ secrets.YCR_TOKEN }}

jobs:
  checkout-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: releases/${{ github.event.inputs.release_version }}

  lint-and-test:
    needs: checkout-release-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: releases/${{ github.event.inputs.release_version }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm ci
      - run: npm run lint
      - run: npm run test

  build-and-push-docker-image:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: releases/${{ github.event.inputs.release_version }}

      - name: Log in to YCR
        run: echo "${{ secrets.YCR_TOKEN }}" | docker login --username oauth --password-stdin cr.yandex

      - name: Build Docker image
        run: |
          IMAGE_NAME="${YCR_REGISTRY_ID}/app:${RELEASE_VERSION}_fix${{ github.run_number }}"
          IMAGE_LATEST="${YCR_REGISTRY_ID}/app:${RELEASE_VERSION}_latest"
          docker build -t $IMAGE_NAME -t $IMAGE_LATEST .

      - name: Push Docker image to YCR
        run: |
          IMAGE_NAME="${YCR_REGISTRY_ID}/app:${RELEASE_VERSION}_fix${{ github.run_number }}"
          IMAGE_LATEST="${YCR_REGISTRY_ID}/app:${RELEASE_VERSION}_latest"
          docker push $IMAGE_NAME
          docker push $IMAGE_LATEST

  create-fix-tag:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: releases/${{ github.event.inputs.release_version }}

      - name: Create Fix Tag
        run: |
          FIX_NUM=${{ github.run_number }}
          git tag v${RELEASE_VERSION}_fix${FIX_NUM}
          git push origin v${RELEASE_VERSION}_fix${FIX_NUM}

  create-fix-issue:
    needs: create-fix-tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          ref: releases/${{ github.event.inputs.release_version }}

      - name: Get previous tag
        id: prev_tag
        run: |
          git fetch --tags
          PREV=$(git tag --sort=-creatordate | grep -E "^(v)?${RELEASE_VERSION}(_fix[0-9]+)?$" | head -n 2 | tail -n 1 || echo "")
          echo "tag=$PREV" >> $GITHUB_OUTPUT

      - name: Get commit list
        run: |
          if [ -z "${{ steps.prev_tag.outputs.tag }}" ]; then
            echo "**Commits (all since beginning):**" > commits.txt
            git log --oneline >> commits.txt || echo "No commits" >> commits.txt
          else
            echo "**Commits since \`${{ steps.prev_tag.outputs.tag }}\`:**" > commits.txt
            git log ${{ steps.prev_tag.outputs.tag }}..HEAD --oneline >> commits.txt || echo "No new commits" >> commits.txt
          fi

      - name: Create or Comment on GitHub Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIX_NUM: ${{ steps.fix_number.outputs.fix_number || github.run_number }}
          AUTHOR: ${{ github.actor }}
          RELEASE_VERSION: ${{ github.event.inputs.release_version }}
          YCR_REGISTRY_ID: ${{ env.YCR_REGISTRY_ID }}
        run: |
          ISSUE_NUMBER=$(gh issue list --limit 1 --search "Release ${RELEASE_VERSION} in:title" --json number --jq '.[0].number' || echo "")
          if [ -n "$ISSUE_NUMBER" ]; then
            gh issue comment "$ISSUE_NUMBER" \
              --body "$(echo -e "Fix \`#${FIX_NUM}\` for Release **${RELEASE_VERSION}**\n Date: $(date -u)\n Author: @${AUTHOR}\n Docker Image: \`${YCR_REGISTRY_ID}/app:${RELEASE_VERSION}_fix${FIX_NUM}\`\n\n"; cat commits.txt)"
          else
            gh issue create \
              --title "Release ${RELEASE_VERSION}" \
              --body "$(echo -e "Fix \`#${FIX_NUM}\` for Release **${RELEASE_VERSION}**\n Date: $(date -u)\n Author: @${AUTHOR}\n Docker Image: \`${YCR_REGISTRY_ID}/app:${RELEASE_VERSION}_fix${FIX_NUM}\`\n\n"; cat commits.txt)"
          fi
